---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[jenkins_master_chef::default]
    attributes:
    verifier:
      name: busser
#      name: inspec
#      inspec_tests:
#        - test/integration/default/jenkins_port.rb
