name 'jenkins_master_chef'
maintainer 'Michael Rollins'
maintainer_email 'michael.rollins@github.com'
license 'all_rights_reserved'
description 'Installs jenkins with plugins'
long_description 'Installs jenkins with plugins'
version '0.1.2'

depends 'apt'
depends 'nginx'
depends 'jenkins'
