name 'jenkins_master_chef'
maintainer 'Michael Rollins'
maintainer_email 'michael.rollins@wholefoods.com'
license 'all_rights_reserved'
description 'Installs jenkins with plugins'
long_description 'Installs jenkins with plugins'
version '0.1.0'

depends 'jenkins'
depends 'apt'
